name: at_flusort
description: "A supporting package providing sorting algorithms for usages in Flutter."
version: 0.0.2
homepage: https://github.com/Krystal0212/at_flusort

environment:
  sdk: ^3.1.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter: